import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Link from "next/link";
import { Toaster, toast } from 'sonner'
import { Playfair_Display } from 'next/font/google';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const playfair = Playfair_Display({
  subsets: ['latin'], // or other subsets you want
  weight: ['400', '700'], // specify weights if needed
  variable: '--font-playfair', // optional CSS variable for using in styles
});

import { FaXTwitter } from "react-icons/fa6";
import { FaFacebook,FaWhatsapp} from "react-icons/fa";
import { IoLogoInstagram, IoLogoLinkedin } from 'react-icons/io5';
export const metadata = {
  title: "Illustrate Marketing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} antialiased`}
      >
        <Navbar/>
        <Toaster />
        <div className="socials1">
            <button className="bg-[#0866ff] p-1 hover:right-0 rounded-md flex gap-2 text-white">
              <span className="text-2xl hover:text-white"><FaFacebook /></span>
              <Link href={'#'}><span className="show-text">Facebook</span></Link>
            </button>
            <button className="bg-pink-600 p-1 hover:right-0 rounded-md flex gap-2 text-white">
              <span className="text-2xl hover:text-white"><IoLogoInstagram /></span>
              <Link href={'https://www.instagram.com/redstackmarketing/'}><span className="show-text">Instagram</span></Link>
            </button>
            <button className="bg-black text-white p-1 hover:right-0 rounded-md flex gap-2">
              <span className="text-2xl"><FaXTwitter/></span>
              <Link href={'#'}><span className="show-text">Twitter/X</span></Link>
            </button>
            <button className="bg-[#0073b1] p-1 hover:right-0 rounded-md flex gap-2 text-white">
              <span className="text-2xl hover:text-white"><IoLogoLinkedin /></span>
              <Link href={'#'}><span className="show-text">LinkedIn</span></Link>
            </button>
          </div>
        {children}
      </body>
    </html>
  );
}
